### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by AhmadEgb** [aaronhnatiw/race-the-web#4]
Hi, could you provide clear instructions on how to install this on windows using the cmd (I already cloned this project)

**Comment by aaronhnatiw** [comment]
Hello,

The [build instructions in the README](https://github.com/aaronhnatiw/race-the-web#compiling) should apply to Windows. Alternatively, you can download and run one of the pre-compiled [releases](https://github.com/aaronhnatiw/race-the-web/releases).

Regards,
Aaron
